//
//  main.cpp
//  default_constructor
//
//  Created by Yujian Zhao on 12/31/24.
//

#include <iostream>

class SimpleNumber{
public:
    int get_number() const {return num_;}
    
    void add(int n){
        num_ += n;
    }
private:
    int num_;
};

class Number{
public:
    Number() = default;
    Number(int initial_value):num_(initial_value){}
    int get_number() const {return num_;}
    
    void add(int n){
        num_ += n;
    }
private:
    int num_;
};

int main(int argc, const char * argv[]) {
    // Since SimpleNumber class does not have a constructor, the compiler automatically generates one.
    SimpleNumber simple_number = SimpleNumber();
    
    // We defined our own constructor so the compiler won't generate one for us. If we still want the one that's automatically generated by the compiler, we need to add it back using "= default".
    Number number = Number();
}
